worker_processes 1;
error_log /tmp/nginx-error.log info;
pid /tmp/nginx-test.pid;

events {
    worker_connections 1024;
}

http {
    include       /etc/nginx/mime.types;
    default_type  application/octet-stream;
    sendfile      on;
    access_log    /tmp/nginx-access.log;
    gzip          on;
    gzip_types    text/plain text/css application/javascript application/json image/svg+xml;

    proxy_cache_path /tmp/nginx_cache levels=1:2 keys_zone=backend_cache:10m max_size=100m inactive=10m use_temp_path=off;

    upstream backend {
        server 127.0.0.1:8000;
    }

    server {
        listen 8080;
        server_name localhost;

        location ^~ /static/ {
            alias /home/mikhail/tpwebproject/static/;
            add_header Cache-Control "public, max-age=604800, immutable";
            expires 7d;
        }

        location ^~ /uploads/ {
            alias /home/mikhail/tpwebproject/media/;
            add_header Cache-Control "public, max-age=604800, immutable";
            expires 7d;
        }

        location / {
            proxy_pass http://backend;
            proxy_set_header Host $host;
            proxy_set_header X-Real-IP $remote_addr;
            proxy_cache backend_cache;
            proxy_cache_valid 200 10m;
        }
    }
}
