# Generated by Django 5.2.8 on 2025-11-12 07:53

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('webproject', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='commentlikes',
            unique_together={('user_id', 'question_id')},
        ),
        migrations.AlterUniqueTogether(
            name='questionlikes',
            unique_together={('user_id', 'question_id')},
        ),
    ]
