# Generated by Django 5.2.8 on 2025-12-21 16:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('webproject', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='answer',
            name='title',
        ),
    ]
