# Generated by Django 5.2.8 on 2025-11-12 08:09

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('webproject', '0002_alter_commentlikes_unique_together_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameField(
            model_name='commentlikes',
            old_name='question_id',
            new_name='comment_id',
        ),
        migrations.AlterUniqueTogether(
            name='commentlikes',
            unique_together={('user_id', 'comment_id')},
        ),
    ]
