# Generated by Django 5.2.8 on 2025-11-12 08:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webproject', '0003_rename_question_id_commentlikes_comment_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='is_active',
            field=models.BooleanField(default=True, help_text='Если True - отображается', verbose_name='Активно'),
        ),
        migrations.AddField(
            model_name='question',
            name='is_active',
            field=models.BooleanField(default=True, help_text='Если True - отображается', verbose_name='Активно'),
        ),
    ]
