# Generated by Django 5.2.8 on 2025-11-12 11:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webproject', '0004_comment_is_active_question_is_active'),
    ]

    operations = [
        migrations.RenameField(
            model_name='tag',
            old_name='name',
            new_name='title',
        ),
        migrations.AddField(
            model_name='comment',
            name='is_correct',
            field=models.BooleanField(default=False, verbose_name='Верный'),
        ),
        migrations.AddField(
            model_name='comment',
            name='likes',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='commentlikes',
            name='status',
            field=models.BooleanField(null=True),
        ),
        migrations.AddField(
            model_name='question',
            name='answers',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='questionlikes',
            name='status',
            field=models.BooleanField(null=True),
        ),
        migrations.AlterField(
            model_name='question',
            name='likes',
            field=models.IntegerField(default=0),
        ),
    ]
