# Generated by Django 5.2.8 on 2025-11-12 11:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webproject', '0005_rename_name_tag_title_comment_is_correct_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='question',
            name='tag_id',
        ),
        migrations.AddField(
            model_name='question',
            name='tags',
            field=models.JSONField(blank=True, default=list, verbose_name='Теги'),
        ),
    ]
