# Generated by Django 5.2.8 on 2025-11-12 12:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webproject', '0007_remove_question_tags_question_tags'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='tags',
            field=models.ManyToManyField(blank=True, max_length=3, to='webproject.tag'),
        ),
    ]
