# Generated by Django 5.2.8 on 2025-11-12 13:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webproject', '0008_alter_question_tags'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='question_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='webproject.question', verbose_name='Вопрос'),
        ),
        migrations.AlterField(
            model_name='question',
            name='tags',
            field=models.ManyToManyField(blank=True, to='webproject.tag'),
        ),
    ]
