# Generated by Django 5.2.8 on 2025-11-12 13:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webproject', '0009_alter_comment_question_id_alter_question_tags'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='avatar',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Аватар пользователя'),
        ),
    ]
