[common]
DEBUG: True

[secret]
SECRET_KEY: django-insecure-#i$$@f#^-c0hcn7nvn@9hm^oh2_ezopo-seagc_ob42v-im6+0

[database]
ENGINE: django.db.backends.postgresql
NAME: tpwebdb
USER: admin
PASSWORD: admin
HOST: 127.0.0.1
PORT: 5432